# Generated by Django 5.2 on 2025-04-15 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('en ligne', 'En ligne'), ('livraison', 'Paiement à la livraison')], default='livraison', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('statut', models.CharField(default='en attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('numero_suivi', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(default='en attente', max_length=20)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.commande')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='produits/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
    ]
